[versions]
elimuModel = "model-2.0.83"
elimuAnalytics = "3.1.28"
elimuContentProvider = "1.2.30"
junit = "4.13.2"
shineButton = "1.0.0"
easingInterpolator = "v1.3.2"

constraintLayout = "2.1.3"
appCompat = "1.4.1"
androidXJunit = "1.1.3"
androidXEspresso = "3.4.0"
kotlin = "2.0.0"

[libraries]
elimu-model = { group = "com.github.elimu-ai", name = "model", version.ref = "elimuModel" }
elimu-analytics = { group = "com.github.elimu-ai", name = "analytics", version.ref = "elimuAnalytics" }
elimu-content-provider = { group = "com.github.elimu-ai", name = "content-provider", version.ref = "elimuContentProvider" }
easing-interpolator = { group = "com.github.MasayukiSuda", name = "EasingInterpolator", version.ref = "easingInterpolator" }
shine-button = { group = "com.sackcentury", name = "shinebutton", version.ref = "shineButton" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidx-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidXJunit" }
androidx-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidXEspresso" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
